version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 4200:4200
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    tty: true

